### ISSUE TITLE
Bring source-based coverage job back in, name it explicitly 'nightly'

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1711] opened 2021-02-08 21:20 UTC
### Tasks

- [ ] Revert the deletion of `.github/workflows/coverage.yml`
- [ ] Check that we're not exceeding the 20 concurrent jobs limit: https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits

**Comment by teor2345** [comment] 2021-02-15 00:14
Duplicate of #1690

**Closed as completed by teor2345** 2021-02-15 00:14 UTC
Labels: A-rust, A-infrastructure

**Comment by teor2345** [comment] 2021-02-15 01:15
This ticket is a duplicate, so its points do not belong in any sprint.
