### ISSUE TITLE
Add a hint to the "Address already in use" error

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zebra#1509] opened 2020-12-13 10:42 UTC
**Suggested Solution**

Add a hint to the "Address already in use" error, like the hint in #1484

**Detailed Logs**

```
Dec 13 12:39:36.866  INFO {zebrad="83e72bdd"}:sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(597795) min_locator_height=597696 locators=[Height(597795), Height(597794), Height(597793), Height(597791), Height(597787), Height(597779), Height(597763), Height(597731), Height(597696)]
Dec 13 12:39:36.867  WARN {zebrad="83e72bdd"}:sync: zebrad::components::sync: error obtaining tips e=
   0: buffered service failed: Address already in use (os error 48)
   1: Address already in use (os error 48)

Location:
   zebrad/src/components/sync.rs:280

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
   0: zebrad::components::sync::obtain_tips
      at zebrad/src/components/sync.rs:255
   1: zebrad::components::sync::sync
      at zebrad/src/components/sync.rs:150
   2: zebrad::commands:: with zebrad="83e72bdd"
      at zebrad/src/commands.rs:56
```

## Error
```
Error: 
   0: buffered service failed: Address already in use (os error 48)
   1: Address already in use (os error 48)
```

## Metadata
|key|value|
|--|--|
|**version**|3.0.0-alpha.0|
|**git commit**|83e72bdd|

## SpanTrace

<details>

```
SpanTrace:
   0: zebrad::components::sync::obtain_tips
             at zebrad/src/components/sync.rs:255
   1: zebrad::components::sync::sync
             at zebrad/src/components/sync.rs:150
   2: zebrad::commands::
           with zebrad="83e72bdd"
             at zebrad/src/commands.rs:56
```
</details>

**Comment by oxarbitrage** [comment] 2020-12-13 13:29
~Duplicate of~ https://github.com/ZcashFoundation/zebra/issues/1484

Edit: not a duplicate, because it's possible to reach this error without reaching the panic in #1484.

**Closed as completed** 2021-01-29 12:36 UTC
Labels: C-bug, A-rust
