### ISSUE TITLE
Follow up on `AdvertiseBlocks`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1393] opened 2020-11-25 19:33 UTC
**Is your feature request related to a problem? Please describe.**

In https://github.com/ZcashFoundation/zebra/pull/1328 we created a first version to handle `AdvertiseBlocks` messages. The solution was described in https://github.com/ZcashFoundation/zebra/issues/1082 as "to get something working" for the first alpha release and implement the alternative solution at a later time. 

**Describe the solution you'd like**
Implement the alternative described in https://github.com/ZcashFoundation/zebra/issues/1082 which consist of:

The procedure above exposes us to a DoS risk, because we blindly download an entire block whenever anyone tells us to.  This is in contrast to the sync process, where we generally download blocks from different peers than the ones who told us about them.

**After the first alpha release**, we should:

- [ ] Download only the block header;
- [ ] Pre-verify the proof of work in the block header;
- [ ] If successful, download and verify the full block.

This is more effort because we need to have a way to pre-verify the proof of work, which requires additional verification plumbing.  So we should do this better alternative after we get something working.

**Describe alternatives you've considered**
No alternatives by now.

**Additional context**

https://github.com/ZcashFoundation/zebra/issues/1082
https://github.com/ZcashFoundation/zebra/pull/1328

No high priority.

**Comment by teor2345** [comment] 2020-11-30 03:03
This ticket is a duplicate of #1166, I've merged the extra information in this ticket into #1166.

**Closed as completed by teor2345** 2020-11-30 03:03 UTC
Labels: C-enhancement
