### ISSUE TITLE
Integrate zk-SNARK parameters directly into the zebrad binary

### ISSUE THREAD

**Issue by ebfull** [ZcashFoundation/zebra#6963] opened 2023-06-14 21:42 UTC
The Sapling zk-SNARK parameters are small enough that it's sensible to store them in the `zebrad` binaries themselves so that users don't have to download and store them separately on disk, which is annoying. The Sprout (groth16) parameters are large, but only a minuscule portion of the Sprout parameters are actually needed by `zebrad` to verify Sprout transactions and these parameters can be stored directly in this repository and `include_bytes!`'d at compile time.

I wrote a [draft PR](https://github.com/zcash/zcash/pull/6661) for `zcashd` where we are considering doing the exact same thing. The PR uses the `wagyu-zcash-parameters` Rust crate so that Sapling parameters are effectively downloaded by `cargo` at compile time. Also in this proposed change for `zcashd`, people who need to create Sprout proofs will have to independently download the Sprout proving key like before, but by default this is not required. `zebrad` would need no such compatibility hack, because as far as I know Sprout proving is not supported nor will it be in the future.

Is this something the project would be interested in adding? If so I might be able to throw a PR up here along the lines of my PR in `zcashd`.

**Comment by teor2345** [comment] 2023-06-14 21:59
I think this would make our CI and zebrad startup more reliable, at the cost of larger build caches and longer link times.

Overall it could be a positive step, but I'd like to check with other Zebra developers first.

We're already using zcash_proofs to download parameters, so it would be easiest for us if we could just switch the functions we're calling in that crate.

**Comment by mpguerra** [comment] 2023-10-24 12:56
is this a duplicate of #7613 ?

**Comment by teor2345** [comment] 2023-10-24 19:20
Yes, I think we accidentally made a duplicate because I'd forgotten about this ticket.

@ebfull no need to make a PR, I opened PR #7800.

**Closed as completed by teor2345** 2023-10-24 19:20 UTC
Labels: C-enhancement, S-needs-triage
