### ISSUE TITLE
Sapling/Orchard Key Agreement and KDF

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#271] opened 2020-02-25 18:36 UTC
All our keys are defined for Sapling and Orchard, we just have to finish the ephemeral - static diffie-hellman interaction to derive the shared secret.

Defined in 
![image](https://user-images.githubusercontent.com/552961/77574604-a7fa9600-6ea8-11ea-9661-e17cedfa57ee.png)
https://zips.z.cash/protocol/protocol.pdf#concretesaplingkeyagreement

and

![image](https://user-images.githubusercontent.com/552961/77574633-b0eb6780-6ea8-11ea-99cd-5f7188020313.png)
https://zips.z.cash/protocol/protocol.pdf#saplinginband

Required for #269.

**Comment by dconnolly** [comment] 2021-01-21 22:30
I think https://github.com/ZcashFoundation/zebra/issues/301 is a duplicate of this.

**Comment by teor2345** [comment] 2022-09-29 00:00
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.

**Closed as not planned by teor2345** 2022-09-29 00:00 UTC
Labels: NU-1 Sapling, A-cryptography
