### ISSUE TITLE
Unable to restart sync after sleep

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zebra#1467] opened 2020-12-07 03:32 UTC
Steps:
1. Put laptop to sleep.
2. Resume from sleep.

What happened:

```
Dec 06 08:43:21.466  INFO {zebrad="5b687f87"}:sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(1066727) min_locator_height=1066628 locators=[Height(1066727), Height(1066726), Height(1066725), Height(1066723), Height(1066719), Height(1066711), Height(1066695), Height(1066663), Height(1066628)]
Dec 06 08:58:07.257  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 09:03:10.056  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 12:22:07.221  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 12:23:11.031  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 12:24:26.030  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 12:25:41.037  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 14:27:05.350  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 16:28:18.875  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 06 19:00:09.620  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 07 01:57:51.719  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 07 03:59:00.760  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 07 04:23:25.061  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 07 04:24:40.062  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 07 04:38:25.574  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 07 04:50:58.092  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Dec 07 05:28:41.665  WARN {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
```

Expected result:
Client finds peers and syncs.

**Comment by teor2345** [comment] 2020-12-07 03:45
Thanks for reporting this bug. It's probably a duplicate of #1435, because sleeping causes network disconnections.

Sleep can disconnect peers:
* immediately, because the TCP stack is shut down by the OS
* after the 2 minute Zebra peer keep alive timeout
* after the 2-30 minute TCP retransmit time-out (depending on the OS or TCP stack)

**Closed as completed by teor2345** 2020-12-07 03:45 UTC
Labels: C-bug
