### ISSUE TITLE
Bump tracing-journald from 0.1.0 to 0.2.2

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3371] opened 2022-01-19 15:00 UTC
## Motivation

We should keep dependencies up to date.

We must fix breaking changes, see logs in https://github.com/ZcashFoundation/zebra/pull/3358

**Comment by mpguerra** [comment] 2022-01-20 15:27
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3371?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment] 2022-01-26 00:01
Duplicate of #2953

**Closed as completed by teor2345** 2022-01-26 00:01 UTC
Labels: C-enhancement
