### ISSUE TITLE
Change `zebrad-hash-lookup` script so it can use `zcashd` or `zebrad`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8829] opened 2024-09-02 18:47 UTC
Currently, the [zebrad-hash-lookup](https://github.com/ZcashFoundation/zebra/tree/main/zebra-utils#zebrad-hash-lookup) bash script can only be used with `zcashd` as the backend as it uses the [getblockheader](https://github.com/ZcashFoundation/zebra/blob/main/zebra-utils/zebrad-hash-lookup#L11) RPC call to get information. 

The call is not supported in zebrad.

This was reported by @dismad in discord, a workaround was given:

```
zcash-cli getbestblockhash | xargs zcash-cli getblock | jq .tx.[0] | xargs -n1 ./txDetails.sh | jq .height  workaround for now 😄
```

Either:

- Implement the workaround to the script
- Implement `getblockheaders` rpc method into zebra. Additional reasons might be wanted to do this.

**Comment by mpguerra** [comment] 2024-10-21 08:18
We should implement `getblockheader` as part of zcashd deprecation. Closing as duplicate of #8442

**Closed as not planned by mpguerra** 2024-10-21 08:18 UTC
Labels: C-testing, A-rpc
