### ISSUE TITLE
collect_chain_hashes re-hashes blocks

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1431] opened 2020-12-02 06:11 UTC
The implementation of `collect_chain_hashes` recomputes block hashes as it traverses the iterator: https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service.rs#L368

But the state already stores all of the relevant block hashes, so this computation is unnecessary.

**Comment by teor2345** [comment] 2020-12-02 06:57
This is a duplicate of #1397, now that the non-finalised state stores PreparedBlocks

**Closed as completed by teor2345** 2020-12-02 06:57 UTC
Labels: C-bug
