### ISSUE TITLE
Detect whether errors are `AlreadyVerified`

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1321] opened 2020-11-18 00:26 UTC
**Is your feature request related to a problem? Please describe.**

The sync logic needs to be able to programmatically detect whether an error is `AlreadyVerified` or not, to avoid restart loops.

**Describe the solution you'd like**

TBD -- @yaahc ?

**Describe alternatives you've considered**

Currently we check this (as a hack) by string comparison on the formatted error.

**Comment by yaahc** [comment] 2020-11-18 00:44
Either replace the format comparisons with this

```rust
        e.downcast_ref()
            .map(|e| matches!(e, VerifyCheckpointError::AlreadyVerified { .. }))
            .unwrap_or(false)
```

or add a helper trait to abstract over this

```rust
use zebra_consensus::VerifyCheckpointError;

trait IsAlreadyVerified {
    fn is_already_verified_error(&self) -> bool;
}

impl IsAlreadyVerified for &(dyn std::error::Error + Send + Sync + 'static) {
    fn is_already_verified_error(&self) -> bool {
        self.downcast_ref()
            .map(|e| matches!(e, VerifyCheckpointError::AlreadyVerified { .. }))
            .unwrap_or(false)
    }
}
```

Then you'd be able to do `if box_error.is_already_verified_error() { .. }`

**Comment by teor2345** [comment] 2021-06-18 08:35
Duplicate of #2339

**Closed as completed by teor2345** 2021-06-18 08:35 UTC
Labels: A-rust, C-cleanup
