### ISSUE TITLE
Bump tracing-subscriber from 0.2.25 to 0.3.6

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3370] opened 2022-01-19 14:58 UTC
## Motivation

We should keep dependencies up to date.

We must fix breaking changes, see logs in https://github.com/ZcashFoundation/zebra/pull/3357

**Comment by teor2345** [comment] 2022-01-26 00:01
Duplicate of #2953

**Closed as completed by teor2345** 2022-01-26 00:01 UTC
Labels: A-dependencies, C-enhancement
