### ISSUE TITLE
Sync failing to find new tips indefinitely

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1003] opened 2020-09-03 00:43 UTC
**Version**

git #main since approximately 96c88093482bc1a2b3437f5239dd9036c647a21c

**Platform**
all

**Description**
During normal `zebrad start` runs inside our Docker containers, eventually the sync will stall out with `zebrad::commands::start::sync: failed to obtain tips, waiting to restart sync`:
![image](https://user-images.githubusercontent.com/552961/92054826-29a9f600-ed5c-11ea-82bc-41b239242066.png)

**Comment by teor2345** [comment] 2020-09-08 23:30
Do we know if #1022 fixed this issue?

I think all our sync PRs have merged now.

**Comment by hdevalence** [comment] 2020-09-09 22:39
I was able to reproduce before but not after, and the problem was noticed right after merging the part of the code #1022 changed. So I assume that that this is fixed.

**Closed as completed by hdevalence** 2020-09-09 22:39 UTC
Labels: C-bug, A-rust
