### ISSUE TITLE
Update redjubjub to 0.5 (or next crates.io release)

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2352] opened 2021-06-18 19:32 UTC
## Motivation

In https://github.com/ZcashFoundation/zebra/pull/2351 we are temporarily pointing to a commit in the main branch of redjubjub. We should point to the next release after it's published.

### Specifications

N/A

### Designs

N/A

## Solution

Update the redjubjub to its next release.

### Alternatives

Keep pointing to the commit, but that should be avoided

## Related Work

Leftover from #2351

**Comment by teor2345** [comment] 2021-11-02 20:30
Duplicate of #2952.

**Closed as completed by teor2345** 2021-11-02 20:30 UTC
Labels: C-enhancement
