### ISSUE TITLE
Eliminate all of the zebrad environment variables

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#826] opened 2020-08-05 07:35 UTC
I think we should eliminate all of these environment variables and use config settings.

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/436_

**Comment by teor2345** [comment] 2020-08-05 07:37
If we eliminate these environmental variables soon, then we'll stop building tests and scripts which depend on them.

**Comment by hdevalence** [comment] 2020-08-05 07:45
Duplicate of #822

**Closed as completed by hdevalence** 2020-08-05 07:45 UTC
Labels: A-rust, C-cleanup
