### ISSUE TITLE
Add a metrics and tracing listener test to the zebrad acceptance tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#995] opened 2020-09-02 07:18 UTC
**Is your feature request related to a problem? Please describe.**

`zebrad`'s acceptance tests don't open metrics and tracing listeners by default.

We should test those code paths.

**Describe the solution you'd like**

Add a separate test to `zebrad/tests/acceptance.rs` which runs `zebrad start` with metrics and tracing listeners on `127.0.0.1:0`. (A zero port means "pick any available port.)

Use the default test config, and modify it to add listeners, like the existing `misconfigured_ephemeral_mode` test:
https://github.com/ZcashFoundation/zebra/blob/main/zebrad/tests/acceptance.rs#L329

The test should check that the command does not panic or exit. Because we expect the command to continue running, the test should kill the command, and check that it was killed, like:
https://github.com/ZcashFoundation/zebra/blob/main/zebrad/tests/acceptance.rs#L342 

**Describe alternatives you've considered**

A. Also add an IPv6 `[::1]:0` test.

But we can't be sure that all our users will have IPv6, so:
* the tests would need to check for "no IPv6" or "keeps running", and
* the "no IPv6" message could be different on different OSes.

Since zebrad doesn't handle raw IP addresses, it is unlikely that we'll write code which works for IPv4, but not IPv6. So this test is a low priority.

B. Do not add any extra tests.

These code paths would not be tested.

**Additional context**

We tried a more complex version of this test in #951, along with other related changes.

**Comment by hdevalence** [comment] 2020-09-02 19:12
I think it could be good if we also tested that changing the tracing filter via the tracing RPC endpoint actually works -- right now, there was a regression in handling the application read/write locks that prevents the endpoint from ever reloading the filter (#1001), and this wasn't caught by any tests because it wasn't tested.  This could either be done together with this issue or as a follow-on.  One reason it might be good to do as a follow-on is that adding the test and having it pass requires debugging the issue and resolving the regression.

**Closed as completed** 2020-09-08 00:05 UTC
Labels: A-rust, good first issue, E-help-wanted, C-enhancement, E-needs-test
