### ISSUE TITLE
Make sure all of our types are Serde'able.

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#137] opened 2019-12-05 23:03 UTC
So that they can be serialized/deserialized via Serde to our storage.

**Comment by hdevalence** [comment] 2020-01-30 20:20
Is #195 a duplicate of this issue?

**Comment by hdevalence** [comment] 2020-03-12 19:22
To figure out whether #195 is a duplicate, we should figure out what types need to be serialized.  One option we could consider is to add Serde bounds to the `ZcashSerialize`/`ZcashDeserialize` traits, but conceptually those are really different kinds of serialization (internal vs external) so it may not be good to mix them (especially if we split out our zcash serialization traits into a separate crate).

**Closed as completed** 2020-06-15 22:08 UTC
