### ISSUE TITLE
Fix documentation links in zebrad::config::ZebradConfig

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7769] opened 2023-10-18 18:26 UTC
## Motivation

The link to the `zebra_network` (and other) field type `Config` goes to the wrong page.

https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html

**Comment by teor2345** [comment] 2023-10-18 20:53
Do we already have a ticket for this?

**Comment by mpguerra** [comment] 2023-10-19 09:29
closed as duplicate of #7048

**Closed as not planned** 2023-10-19 09:29 UTC
Labels: A-docs
