### ISSUE TITLE
Implement Orchard binding verification key derivation

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2102] opened 2021-05-04 19:18 UTC
Similar to `ShieldedData` for Sapling, we need to derive and validate the Orchard binding verification key.

**Comment by teor2345** [comment] 2021-05-06 19:48
I think this might be a duplicate of #1979. We have an orchard::ShieldedData and orchard::AuthorizedAction as part of the transaction v5 RFC design, they just haven't been implemented yet.

**Comment by teor2345** [comment] 2021-05-06 19:49
> I think this might be a duplicate of #1979. We have an orchard::ShieldedData and orchard::AuthorizedAction as part of the transaction v5 RFC design, they just haven't been implemented yet.

Actually I think it might be the description that's the issue here - we don't just need to store the data, we also need to process it.

@dconnolly can you update the description to talk about binding signature verification and AuthorizedAction?

**Closed as completed** 2021-08-16 19:16 UTC
Labels: A-rust, NU-5
