### ISSUE TITLE
Fix "The resource already exists" Google Cloud errors

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5227] opened 2022-09-21 22:40 UTC
## Motivation

When CI fails and does not delete an instance or disk, future CI runs will always fail, until:
- the instance or disk is manually deleted by a developer,
- the instance or disk is automatically deleted after 2-3 days, or
- the PR branch is updated with a new commit hash.

Since this is tricky to diagnose and fix, we should change the workflows to stop it happening.

### Logs

> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
 - The resource 'projects/zealous-zebra/zones/us-central1-a/instances/sync-past-checkpoint-5216-merge-19c990b' already exists

https://github.com/ZcashFoundation/zebra/actions/runs/3098898423/jobs/5022722988#step:7:78

## Suggested Solutions

Fix instance, instance template, and disk names by:

- Adding an HHMMSS timestamp to make the resource name unique

OR

- Running the delete step before creating test resources, as well as running it afterwards

## Related Issues

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/5216#issuecomment-1254301934_

**Comment by teor2345** [comment] 2022-09-21 22:41
This is a low priority because it doesn't happen very often

**Comment by teor2345** [comment] 2022-12-01 02:35
We haven't seen this for a few months.

**Comment by teor2345** [comment] 2022-12-08 08:47
I've seen this a few times recently.

**Comment by mpguerra** [comment] 2023-01-18 11:16
I think we should just close this for good, it seems to be hard to reproduce and we're going to look into re-designing CI anyway

**Closed as completed by mpguerra** 2023-01-18 11:16 UTC
Labels: C-bug, A-devops, I-integration-fail
