### ISSUE TITLE
Try harder to find more peers on failure

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#738] opened 2020-07-23 11:38 UTC
Sometimes, the sync service hangs with the following errors:
* WrongBlock (1-2)
* ClientRequestTimeout (many)

Sometimes it will get in a loop of logging peer networking errors, other times it will stall and not log anything.

My network is sometimes slow, unreliable, and fails IPv6 (but pretends to support it). I've also reduced the configured peer limits, to speed up sync tests with local peers.

This error is reproducible approximately every 2-4 fresh syncs on my network.

**Comment by hdevalence** [comment] 2020-07-24 17:51
Just to clarify, is this a problem with a lack of available peers (i.e., the network layer is failing to crawl and connect to enough peers) or an issue about the way that the syncer tries to download blocks and handles (or doesn't handle) errors?

Because we know that the syncer doesn't really work properly yet, my prior is that the problem is with the syncer logic rather than the availability of peers, but we could get more information by looking at the metrics from the peer set using grafana -- it reports the number of ready/unready peers as well as information about the number of candidates it's attempted to connect to, etc.

**Comment by dconnolly** [comment] 2020-08-13 23:16
Closing for now, we should reopen if it happens again.

**Closed as completed by dconnolly** 2020-08-13 23:16 UTC
Labels: C-bug
